name: functa
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - pip
  - pip:
    - objaverse
    - wandb
    - gitpython
    - opencv-python
    - libigl
    - jupyterlab
    - jupyter
    - bpy
    - mathutils
